channels:
  - conda-forge
  - defaults
dependencies:
  - python=3
  - pip
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::cudatoolkit=11.0
  - transformers
  - datasets
  - dvc
  - wandb
  - tqdm
  - jq
  - just
  - pip
    - git+https://github.com/aseifert/errant.git@feature/compare_m2_json  # patched for json export
    - simpletransformers
