channels:
  - conda-forge
  - defaults
dependencies:
  - python=3
  - pip
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::cudatoolkit=11.0
  - transformers
  - datasets
  - dvc
  - wandb
  - jq
  - pip
    - errant
    - simpletransformers
